"""Writers for Sentinelle validation reports and plans."""

from __future__ import annotations

import json
from pathlib import Path


def _fmt_candidate_table(candidates: list[dict], empty_text: str) -> str:
    if not candidates:
        return empty_text + "\n"
    lines = ["| Column | Score | Unique values | Unique ratio | Reasons |", "|---|---:|---:|---:|---|"]
    for item in candidates:
        reasons = "; ".join(item.get("reasons", []))
        lines.append(
            f"| `{item.get('name')}` | {item.get('score', 0):.2f} | "
            f"{item.get('n_unique', '')} | {item.get('unique_ratio', 0):.2f} | {reasons} |"
        )
    return "\n".join(lines) + "\n"


def _fmt_risk_table(risks: list[dict]) -> str:
    lines = ["| Severity | Risk | Evidence | Recommendation |", "|---|---|---|---|"]
    for risk in risks:
        lines.append(
            f"| {risk.get('severity', '')} | {risk.get('risk', '')} | "
            f"{risk.get('evidence', '')} | {risk.get('recommendation', '')} |"
        )
    return "\n".join(lines) + "\n"


def _fmt_score(value) -> str:
    if value is None:
        return ""
    try:
        return f"{float(value):.4f}"
    except (TypeError, ValueError):
        return str(value)


def _fmt_cv_benchmark_section(benchmark: dict | None) -> list[str]:
    if not benchmark or not benchmark.get("results"):
        return []

    results = benchmark.get("results", {})
    lines = [
        "## CV Strategy Comparison",
        "",
        "This comparison uses simple baseline models. It is not intended to optimize leaderboard performance. "
        "Its purpose is to compare validation designs under a fixed modeling procedure.",
        "",
        f"- Model used: **{benchmark.get('model_name', 'unknown')}**",
        f"- Metric: **{benchmark.get('metric_name', 'unknown')}**",
        f"- Rows evaluated: **{benchmark.get('n_rows_evaluated', 'unknown')}**",
        "",
        "The requested split count is treated as a maximum. Some validation designs may use fewer folds when "
        "limited by the number of groups, periods, or class counts.",
        "",
        "| validation_design | mean_score | std_score | n_folds | requested_n_splits | actual_n_folds | interpretation |",
        "|---|---:|---:|---:|---:|---:|---|",
    ]
    for split_name, result in results.items():
        lines.append(
            f"| `{split_name}` | {_fmt_score(result.get('mean_score'))} | "
            f"{_fmt_score(result.get('std_score'))} | {result.get('n_folds', '')} | "
            f"{result.get('requested_n_splits', '')} | {result.get('actual_n_folds', '')} | "
            f"{result.get('interpretation', '')} |"
        )

    adjustments = [
        (split_name, result.get("adjustment_note"))
        for split_name, result in results.items()
        if result.get("adjustment_note")
    ]
    if adjustments:
        lines.extend(["", "Fold-count adjustments:", ""])
        for split_name, note in adjustments:
            lines.append(f"- `{split_name}`: {note}")

    skipped = benchmark.get("skipped", [])
    if skipped:
        lines.extend(["", "Skipped split designs and notes:", ""])
        for item in skipped:
            lines.append(f"- `{item.get('split', 'unknown')}`: {item.get('reason', '')}")

    warning = benchmark.get("optimism_warning")
    if warning and warning.get("detected"):
        lines.extend(
            [
                "",
                "### Optimism warning",
                "",
                warning.get("message", ""),
                "",
                "Random KFold achieved a more favorable score than the safer split. This may indicate optimistic "
                "validation caused by temporal/group leakage. Treat random KFold as a diagnostic baseline, not as "
                "the primary validation estimate.",
            ]
        )

    lines.append("")
    return lines


def write_markdown_report(plan: dict, output_path: str) -> None:
    """Write a human-readable validation design report."""

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    recommendation = plan.get("recommendation", {})
    data_structure = plan.get("data_structure", {})

    lines = [
        "# Validation Design Report",
        "",
        "Generated by Sentinelle Validation Agent.",
        "",
        "## Summary",
        "",
        f"- Detected task type: **{plan.get('task_type', 'unknown')}**",
        f"- Detected data structure: **{recommendation.get('detected_structure', data_structure.get('structure', 'unknown'))}**",
        f"- Risk level: **{recommendation.get('risk_level', 'unknown')}**",
        f"- Primary validation design: **{recommendation.get('primary_cv', 'unknown')}**",
        f"- Recommended group column: `{recommendation.get('recommended_group_col')}`",
        f"- Recommended time column: `{recommendation.get('recommended_time_col')}`",
        "",
        "## Candidate time columns",
        "",
        _fmt_candidate_table(plan.get("time_cols", []), "No strong time-like columns detected."),
        "## Candidate group/entity columns",
        "",
        _fmt_candidate_table(plan.get("group_cols", []), "No strong group/entity columns detected."),
        "## Candidate id columns",
        "",
        _fmt_candidate_table(plan.get("id_cols", []), "No strong row identifier columns detected."),
        "## Candidate block/category columns",
        "",
        _fmt_candidate_table(plan.get("block_cols", []), "No candidate block/category columns detected."),
        "## Leakage risks",
        "",
        _fmt_risk_table(plan.get("risks", [])),
        "## Recommended primary validation design",
        "",
        f"**{recommendation.get('primary_cv', 'unknown')}**",
        "",
        recommendation.get("explanation", ""),
        "",
        "## Secondary validation designs",
        "",
    ]
    for item in recommendation.get("secondary_cv", []):
        lines.append(f"- {item}")
    lines.extend(["", "## Validation designs to avoid", ""])
    for item in recommendation.get("avoid", []):
        lines.append(f"- {item}")
    benchmark_lines = _fmt_cv_benchmark_section(plan.get("cv_benchmark"))
    if benchmark_lines:
        lines.extend([""] + benchmark_lines)
    lines.extend(
        [
            "",
            "## Reproducible split code",
            "",
            "See `split_code.py` in the same output directory. Review the inferred column defaults before using them in modeling.",
            "",
            "## Limitations",
            "",
            "- Heuristics identify candidates; they do not prove causal or temporal availability.",
            "- Confirm target availability, feature timing, and grouping semantics with domain knowledge.",
            "- Small datasets may require fewer folds or simpler holdouts.",
            "- Report subgroup or block metrics when important categories are imbalanced.",
            "",
        ]
    )
    output.write_text("\n".join(lines), encoding="utf-8")


def write_json_plan(plan: dict, output_path: str) -> None:
    """Write a machine-readable validation plan."""

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(plan, indent=2, default=str), encoding="utf-8")
