"""Generate reusable split-code templates from a validation plan."""

from __future__ import annotations

import json


def _repr_or_none(value):
    return repr(value) if value is not None else "None"


def generate_split_code(plan: dict) -> str:
    """Return Python code containing reusable split functions.

    Inferred column names are inserted only as default values. Users can pass
    explicit column names when applying the generated code to a new dataset.
    """

    recommendation = plan.get("recommendation", {})
    group_col = recommendation.get("recommended_group_col")
    time_col = recommendation.get("recommended_time_col")
    block_cols = recommendation.get("recommended_block_cols", [])
    metadata = {
        "detected_structure": recommendation.get("detected_structure"),
        "primary_cv": recommendation.get("primary_cv"),
        "recommended_group_col": group_col,
        "recommended_time_col": time_col,
        "recommended_block_cols": block_cols,
    }

    return f'''"""Reusable validation split helpers generated by Sentinelle Validation Agent.

Generated plan summary:
{json.dumps(metadata, indent=2)}
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.model_selection import GroupKFold, KFold, TimeSeriesSplit


DEFAULT_GROUP_COL = {_repr_or_none(group_col)}
DEFAULT_TIME_COL = {_repr_or_none(time_col)}
DEFAULT_BLOCK_COLS = {block_cols!r}


def make_kfold_splits(df, n_splits=5, shuffle=True, random_state=42):
    """Yield IID KFold train/validation index arrays.

    Use this only when rows are plausibly independent and identically
    distributed. It is included as a baseline, not as the safest default for
    grouped, temporal, or panel data.
    """
    splitter = KFold(n_splits=n_splits, shuffle=shuffle, random_state=random_state if shuffle else None)
    yield from splitter.split(df)


def make_group_kfold_splits(df, group_col=DEFAULT_GROUP_COL, n_splits=5):
    """Yield GroupKFold splits that keep each group in one fold."""
    if group_col is None:
        raise ValueError("group_col is required for GroupKFold splits.")
    if group_col not in df.columns:
        raise ValueError(f"group_col {{group_col!r}} is not present in df.")
    n_groups = df[group_col].nunique(dropna=True)
    if n_groups < 2:
        raise ValueError("At least two groups are required for grouped validation.")
    n_splits = min(n_splits, int(n_groups))
    splitter = GroupKFold(n_splits=n_splits)
    yield from splitter.split(df, groups=df[group_col])


def make_leave_one_period_out_splits(df, time_col=DEFAULT_TIME_COL):
    """Yield splits where each observed period is used once as validation."""
    if time_col is None:
        raise ValueError("time_col is required for leave-one-period-out splits.")
    if time_col not in df.columns:
        raise ValueError(f"time_col {{time_col!r}} is not present in df.")
    periods = pd.Series(df[time_col].dropna().unique()).sort_values(kind="mergesort").tolist()
    indices = np.arange(len(df))
    for period in periods:
        valid_mask = df[time_col].eq(period).to_numpy()
        train_idx = indices[~valid_mask]
        valid_idx = indices[valid_mask]
        if len(train_idx) and len(valid_idx):
            yield train_idx, valid_idx


def make_time_blocked_splits(df, time_col=DEFAULT_TIME_COL, n_splits=5, min_train_periods=1):
    """Yield forward-chaining blocked time splits.

    Rows are ordered by unique time values. Each validation fold contains one
    or more future time blocks, and training uses only earlier time blocks.
    """
    if time_col is None:
        raise ValueError("time_col is required for time-blocked splits.")
    if time_col not in df.columns:
        raise ValueError(f"time_col {{time_col!r}} is not present in df.")

    ordered_periods = pd.Series(df[time_col].dropna().unique()).sort_values(kind="mergesort").tolist()
    if len(ordered_periods) <= min_train_periods:
        raise ValueError("Not enough periods for a blocked time split.")

    candidate_periods = ordered_periods[min_train_periods:]
    fold_periods = np.array_split(candidate_periods, min(n_splits, len(candidate_periods)))
    indices = np.arange(len(df))
    for valid_periods in fold_periods:
        valid_periods = list(valid_periods)
        if not valid_periods:
            continue
        first_valid_pos = ordered_periods.index(valid_periods[0])
        train_periods = set(ordered_periods[:first_valid_pos])
        valid_periods_set = set(valid_periods)
        train_mask = df[time_col].isin(train_periods).to_numpy()
        valid_mask = df[time_col].isin(valid_periods_set).to_numpy()
        train_idx = indices[train_mask]
        valid_idx = indices[valid_mask]
        if len(train_idx) and len(valid_idx):
            yield train_idx, valid_idx


def make_sklearn_time_series_splits(df, time_col=DEFAULT_TIME_COL, n_splits=5):
    """Yield TimeSeriesSplit indices after sorting rows by time_col."""
    if time_col is None:
        raise ValueError("time_col is required for TimeSeriesSplit.")
    if time_col not in df.columns:
        raise ValueError(f"time_col {{time_col!r}} is not present in df.")
    ordered_index = df.sort_values(time_col, kind="mergesort").index.to_numpy()
    splitter = TimeSeriesSplit(n_splits=n_splits)
    positional = np.arange(len(ordered_index))
    for train_pos, valid_pos in splitter.split(positional):
        yield ordered_index[train_pos], ordered_index[valid_pos]
'''
